name: "Publish Release"
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Create deploy_date from date
        id: today
        run: |
          deploy_date=$(TZ=US/Eastern date +%Y.%m.%d__%H_%M)
          echo "deploy_date=$deploy_date" >> $GITHUB_OUTPUT
      - name: Title & publish draft release
        id: publish_release
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        uses: release-drafter/release-drafter@v6.4.0
        with:
          tag: ${{ steps.today.outputs.deploy_date }}
          name: ${{ steps.today.outputs.deploy_date }}
          version: ${{ steps.today.outputs.deploy_date }}
          publish: true
